### ISSUE TITLE
Broken Link for the index.html

### ISSUE THREAD

**Issue by Buedenbender** [guggero/www.node-recovery.com#1]
I considered creating an PR but I think its probably faster done with an issue.
![grafik](https://user-images.githubusercontent.com/38650857/201451477-e09e8fe3-3bcc-435d-883d-675952a97dbe.png)

The first link [Official lnd recovery guide](https://docs.lightning.engineering/lightning-network-tools/lnd/recovery) to https://docs.lightning.engineering/lightning-network-tools/lnd/recovery does not work anymore.

I gues the correct "new" link should be:
https://docs.lightning.engineering/lightning-network-tools/lnd/disaster-recovery

**Comment by guggero** [comment]
Thanks a lot, I updated the link!
